version: 2.1
jobs:
  test:
    working_directory: ~
    docker:
      - image: unityci/editor:2020.1.13f1-webgl-0
    steps:
      - checkout:
          path: unity-material-library
      - run: apt-get install -y ssh git xvfb
      - run: git clone https://github.com/oparaskos/unity-material-library-test-project.git
      - run: xvfb-run /opt/unity/Editor/Unity -projectPath unity-material-library-test-project -batchmode -runTests -nographics -logFile out.log -username $UNITY_USERNAME -password $UNITY_PASSWORD –quit

workflows:
  test:
    jobs:
      - test
